name: Terraform CI/CD

on:
  push:
    branches:
      - development

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print environment
        run: env  
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 
    
      - name: Terraform Init
        run: terraform init

      - name: Check Terraform Formatting
        run: terraform fmt -check
      
      - name: Assume AWS Role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1
        with:
           role-to-assume: arn:aws:iam::738322481337:role/git-access
           aws-region: us-east-1
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/development'
        run: terraform apply -auto-approve tfplan
